# Generated by Django 5.1.6 on 2025-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PetsAdoption", "0002_alter_pet_pet_lever"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="avilability",
            field=models.BooleanField(default=True),
        ),
    ]
