# Generated by Django 5.1.3 on 2025-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetsAdoption', '0003_pet_avilability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='compatibility',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
