# Generated by Django 5.1.3 on 2025-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetsAdoption', '0004_remove_pet_compatibility_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
