# Generated by Django 5.1.3 on 2025-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetsAdoption', '0007_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('DESCONOCIDO', 'Desconocido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('CONEJO', 'Conejo'), ('HAMSTER', 'Hamster'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
